- name: python
  url: https://www.python.org/ftp/python/3.11.4/python-3.11.4-amd64.exe

- name: pycharm
  url: https://download.jetbrains.com/python/pycharm-community-2023.1.3.exe

- name: git
  url: https://github.com/git-for-windows/git/releases/download/v2.41.0.windows.1/PortableGit-2.41.0-64-bit.7z.exe

- name: mobaxterm
  url: https://github.com/RipplePiam/MobaXterm-Chinese-Simplified/archive/refs/tags/v0.23.109.zip

- name: v2ray
  url: https://github.com/2dust/v2rayN/releases/download/3.27/v2rayN-Core.zip

- name: docker
  url: https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe

- name: mysql
  url: https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.33-winx64.zip

- name: redis
  url: https://github.com/tporadowski/redis/releases/download/v5.0.14/Redis-x64-5.0.14.zip

- name: mongodb
  url: https://fastdl.mongodb.org/windows/mongodb-windows-x86_64-6.0.7.zip

- name: elasticsearch
  url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.8.2-windows-x86_64.zip

- name: rabbitmq
  url: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.12.1/rabbitmq-server-3.12.1.exe

- name: nginx
  url: https://nginx.org/download/

- name: node.js
  url: https://nodejs.org/dist/v18.16.1/node-v18.16.1-x64.msi
  commands:
    - npm config set prefix "D:\dev\nodejs"

- name: vue.js
  url: https://cn.vuejs.org/
